# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b080a0ef14e9a10f9f7174613a280b9ee91548a73a5091d406f2d1e0984510b88bc9e54aabacd4b70bad4861aaed13a98e258121b732a1ddeecde4f7e51a893

test:
  secret_key_base: 86fa0d987b94da6641e90f37cbab32fa35a85f570a81e7f34d129389ee0b248a9a68fbc18f1a05de133c54a8aef0608d5b863cd3db753ea35e20edf31fbb449a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
